apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: business-unit
spec:
  # Since this is for a namespace repository, the format should be unstructured
  sourceFormat: unstructured
  git:
   repo: git://github.com/alain-baxter/acm-demo.git
   branch: main
   dir: business-unit-namespace
   auth: none
